[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Categories"
pageRef = "categories"
weight = 20

[[main]]
name = "Tags"
pageRef = "tags"
weight = 30

[[main]]
identifier = "search"
weight = 99
[main.params]
action = "search"

[[main]]
identifier = "locale"
weight = 100
[main.params]
action = "locale"

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10
