baseURL = "https://fabioluciano.dev"
languageCode = "en-us"
title = "Fábio Luciano"
theme = "hugo-theme-stack"
copyright = "Fábio Luciano"
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[security.exec]
allow = ["^asciidoctor$"]


[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[markup]
[markup.asciidocext]
extensions = ["asciidoctor-diagram"]
workingFolderCurrent = true
trace = true
failureLevel = "fatal"

[markup.asciidocext.attributes]
"toc" = ""
"docinfo" = "shared"
"nofooter" = ""
"skip-front-matter" = ""
"icons" = "font"
"sectlinks" = ""
"sectanchors" = ""
"figure-caption!" = ""
"source-highlighter" = "highlightjs"
"experimental" = "true"
"plantuml-format" = "png"
"allow-uri-read" = ""


[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar.avatar]
enabled = false

[params.article]
math = false
toc = true
readingTime = true

[params.comments]
enabled = true
provider = "disqus"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = []

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/fabioluciano"

[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/fabioluciano"

[menu.social.params]
icon = "brand-twitter"

[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200
