baseURL = "https://fabioluciano.dev"
defaultContentLanguage = "pt"
theme = "congo"
title = "Fábio Luciano"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
removePathAccents = true

[menu]
  [[menu.main]]
    identifier = "resume"
    pre = ""
    post = ""
    name = "Curriculo"
    url = "https://me.fabioluciano.dev/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categorias"
    url = "/categories/"
    weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[author]
  name = "Fábio Luciano"
  email = "fabio@naoimporta.com"
  link = "https://fabioluciano.dev"

[Permalinks]
  posts = "post/:slug"
