baseURL = "https://blog.fabioluciano.dev"
defaultContentLanguage = "pt"
theme = "LoveIt"
title = "Fábio Luciano"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
removePathAccents = true

[menu]
  [[menu.main]]
    identifier = "resume"
    pre = ""
    post = ""
    name = "Curriculo"
    url = "https://me.fabioluciano.dev/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categorias"
    url = "/categories/"
    weight = 4

[params]
  version = "0.2.X"
  defaultTheme = "auto"
  gitRepo = "https://github.com/fabioluciano/blog.fabioluciano.dev"
  dateFormat = "2006-01-02"
  
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

  [params.footer]
    enable = true
    hugo = false
    copyright = false

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.home.profile]
    enable = true
    gravatarEmail = "fabio@naoimporta.com"
    social = true
  
  [params.social]
    GitHub = "fabioluciano"
    Linkedin = "fabioluciano"
    Twitter = "fabioluciano"
    Instagram = "fabioluciano"
    Telegram = "fabioluciano"
    Keybase = "fabioluciano"
    Reddit = "fabioluciano"
    Spotify = "fabiolucianobr"
    Email = "fabio@naoimporta.com"
    RSS = true

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false

    [params.page.toc]
      enable = false

    [params.page.code]
      copy = true
      maxShownLines = 20

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      HackerNews = true
      Reddit = true
      Pocket = true
    [params.page.comment]
      enable = true

      [params.page.comment.telegram]
        enable = true
        siteID = "I2U0ZuYW"
        limit = 15
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[author]
  name = "Fábio Luciano"
  email = "fabio@naoimporta.com"
  link = "https://fabioluciano.dev"

[Permalinks]
  posts = "post/:slug"
