baseURL: "https://fabioluciano.dev/"
title: Fábio Luciano
paginate: 5
theme: "LoveIt"
defaultContentLanguage: en
languageCode: en
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45
disqusShortname: fabiolucianodev
minify:
  disableXML: true

params:
  version: 0.2.X
  defaultTheme: light
  gitRepo: https://github.com/fabioluciano/fabioluciano.dev
  footer:
    enable: false
  page:
    toc:
      enable: false
    code:
      maxShownLines: 50
    comment:
      telegram:
        enable: true
        siteID: I2U0ZuYW
  search:
    enable: true
    contentLength: 4000
    placeholder: ""
    maxResultLength: 10
    snippetLength: 30
    highlightTag: "em"
    absoluteURL: false

removePathAccents: true
permalinks:
  posts: ":slug"
taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  highlight:
    noClasses: false
