baseURL = "https://fabioluciano.dev"
languageCode = "en-us"
title = "Fábio Luciano"
theme="archie"
copyright = "Fábio Luciano"
pygmentsstyle = "tango"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="light"
	useCDN=true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/fabioluciano/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/fabioluciano/"

[[params.social]]
name = "Currículo"
icon = "user"
url = "https://me.fabioluciano.dev/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Currículo"
url = "https://me.fabioluciano.dev/"
weight = 6